spark.sql.extensions                   org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,io.delta.sql.DeltaSparkSessionExtension

# Iceberg settings
spark.sql.catalog.demo                 org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.demo.type            rest
spark.sql.catalog.demo.uri             http://rest:8181
spark.sql.catalog.demo.io-impl         org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.demo.warehouse       s3://warehouse/wh/
spark.sql.catalog.demo.s3.endpoint     http://minio:9000
spark.sql.defaultCatalog               demo

# Delta settings 
spark.sql.catalog.delta_catalog           org.apache.spark.sql.delta.catalog.DeltaCatalog
spark.sql.catalog.delta_catalog.type      hadoop
spark.sql.catalog.delta_catalog.warehouse s3://warehouse/delta/

# Spark settings
spark.master                           spark://spark-master:7077
spark.eventLog.enabled                 true
spark.eventLog.dir                     /home/iceberg/spark-events
spark.history.fs.logDirectory          /home/iceberg/spark-events
spark.sql.catalogImplementation        in-memory
spark.jars                             /opt/spark/jars/iceberg-spark-runtime-4.0_2.13-1.10.0.jar,/opt/spark/jars/iceberg-aws-bundle-1.10.0.jar,/opt/spark/jars/delta-spark_4.0_2.13-4.2.0.jar,/opt/spark/jars/delta-storage-4.2.0.jar
spark.log.level                         WARN


